# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19apTucWclJ5RqpNWW_jno45yKeVKsK-y
"""

from google.colab import files
import io
import pandas as pd

print("Please upload the CSV file.")
uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))
  # Read the CSV file into a pandas DataFrame
  df = pd.read_csv(io.StringIO(uploaded[fn].decode('utf-8')))
  print(f"DataFrame '{fn}' loaded successfully.")
  print(df.head())



numerical_df = df.select_dtypes(include=['number'])

if not numerical_df.empty:
    statistics_df = numerical_df.agg(['mean', 'min', 'max'])
    print("Calculated statistics for numerical columns:")
    display(statistics_df)
else:
    print("No numerical columns found in the DataFrame.")

def is_palindrome(text):
  """Checks if a given string is a palindrome (reads the same forwards and backwards)."""
  # Normalize the string: remove spaces and convert to lowercase
  normalized_text = ''.join(filter(str.isalnum, text)).lower()
  return normalized_text == normalized_text[::-1]

user_input = input("Enter a string to check if it's a palindrome: ")

if is_palindrome(user_input):
  print(f'\"' + user_input + '\" is a palindrome.')
else:
  print(f'\"' + user_input + '\" is not a palindrome.')